name: Publish Package to npmjs
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
      # - name: Configure artifactory
        env:
          ARTIFACTORY_USEREMAIL: ${{ secrets.ARTIFACTORY_USEREMAIL }}
          ARTIFACTORY_PASSWORD: ${{ secrets.JFROG_NPM_TOKEN }}
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      - run: 
         echo "email = hamdaniymelissa@gmail.com
                always-auth = true
                registry=https://trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/
                //trialk033s3.jfrog.io/artifactory/api/npm/paris-npm/:_authToken=cmVmdGtuOjAxOjE3NjYxMzQzMjc6WFhlSHRxQ0hSZTVoS2tKYmxrR0hhN0w2d1p0" > ~/.npmrc


      - name: Push to artifactory
        env:
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
        run: npm publish --registry https://$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/     

      
