name: On push
on:
  push:
    branches:
      - main
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      - uses: ./.github/actions/container
        with:
          docker_repo: trialk033s3.jfrog.io/docker-trial
          docker_user: melissa
          docker_token: ${{ secrets.JFROG_NPM_TOKEN }}
