# name: Publish Package to npmjs
name : Publish build in artifactory
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: jfrog auth 
        uses: jfrog/setup-jfrog-cli@v4

        env: 
          JF_URL: https://trialk033s3.jfrog.io/
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          
      # - name : jfrog check version
      #   run: jf --version
        
      - run:
          |
          # Ping the server
          jf rt ping
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
      # - name: Set up nodejs
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16'
          
      # - name: Cache node modules
      #   id: cache-npm
      #   uses: actions/cache@v3
      #   env:
      #     cache-name: cache-node-modules
      #   with:
      #     # npm cache files are stored in `~/.npm` on Linux/macOS
      #     path: ~/.npm
      #     key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-build-${{ env.cache-name }}-
      #       ${{ runner.os }}-build-
      #       ${{ runner.os }}-

      # - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      #   name: List the state of node modules
      #   continue-on-error: true
      #   run: npm list

      # - name: Install dependencies
      #   run: npm install
      # - name: Configure artifactory
      #   env:
      #     ARTIFACTORY_USEREMAIL: ${{ secrets.ARTIFACTORY_USEREMAIL }}
      #     ARTIFACTORY_PASSWORD: ${{ secrets.JFROG_NPM_TOKEN }}
      #     ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      #   run:
      #     |
      #     echo "email = $ARTIFACTORY_USEREMAIL
      #           always-auth = true
      #           registry=https://$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/
      #           //$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/:_authToken=$ARTIFACTORY_PASSWORD" > ~/.npmrc


      # - name: Push to artifactory
      #   env:
      #     ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      #   run: npm publish --registry https://$ARTIFACTORY_URL/artifactory/api/npm/paris-npm/     

      
